init_from: "scratch"
resume_ckpt_step: null
ckpt_filename_format: "model_{step:05d}.pt"

# LOGGING
wandb_log: true
wandb_project: "gpt2"
wandb_run_name: null
log_dir: "log"
log_file: "log.txt"


# TRAINING CONFIGS
total_batch_size: 524288  # in tokens, 2 ** 19 (a "nice" number)
batch_size: 2  # micro batch size
context_length: 1024  # sequence length
vocab_size: 50304  # gpt vocab size = 50257, padded to 50304 to make it a multiple of 64
max_lr: 6e-4
min_lr_factor: 0.1
warmup_steps: 715  # gpt3 used 375e6 warmup tokens.  375e6 / TOTAL_BATCH_SIZE = 715
max_steps: 19073  # TOTAL_TOKENS (10e9) / TOTAL_BATCH_SIZE = 19073
ckpt_interval: 100
weight_decay: 0.1
eval_interval: 100
val_loss_steps: 20

# DATA CONFIGS
data_root: "gpt2/edu_fineweb10B"
